### ISSUE TITLE
outRepBuff

### ISSUE THREAD

**Issue by meddd** [saper-2/hidups-comm-test#1]
Hi,
I have start to used your sofware.
I can find USB devices with showing result.
But when I run first command QS i got
An unhandled exception of type 'System.IndexOutOfRangeException' occurred in UPSCommTest.exe
in FORM1.cs in line 350.:   outRepBuff[0] = 0x00;
Can You check this error.

**Comment by saper-2** [comment]
I think your UPS just don't simulate serial protocol over hid. I have this with greencell UPS too 😑 , they use as command getStringDescriptor with different string numbers (0,1 (and 2 if I remember right) are standard for manufacturer & model (& S/N), while higher numbers are manufacturer specific). e.g. if I call getStringDescriptor(6) then UPS respond with string that have UPS status in voltronic-qs format... 🤦 

So far I didn't managed to get this programmed in Windows and C# .Net... Only under Linux and using Python I managed to talk to UPS that use this retarded protocol 😑
